### ISSUE TITLE
Problem with Javascript Intro to Labs Function Lesson - index.js test if statements sayHiToGrandma

### ISSUE THREAD

**Issue by jenlaister** [learn-co-curriculum/javascript-intro-to-functions-lab#12]
Hi, I'm experiencing an issue with the Javascript Intro to Labs Function. When I run the solutions for the below test problems, learn IDE will return one of the below test problems that has already been solved. There seems to be a glitch with the below problems on learn IDE for this lesson, can someone please look into this?

1) sayHiToGrandma(string) returns "I can't hear you!" if `string` is lowercase:  
     Error: Expected undefined to equal 'I can\'t hear you!'  
      at assert (node_modules/expect/lib/assert.js:29:9)  
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)  
      at Context.<anonymous> (test/index-test.js:40:37)                                         

2) sayHiToGrandma(string) returns "YES INDEED!" if `string` is uppercase:  
     Error: Expected undefined to equal 'YES INDEED!'  
      at assert (node_modules/expect/lib/assert.js:29:9)  
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)  
      at Context.<anonymous> (test/index-test.js:44:37)    

3) sayHiToGrandma(string) returns "I love you, too." if `string` is "I love you, Grandma."`:  
     Error: Expected undefined to equal 'I love you, too.'  
      at assert (node_modules/expect/lib/assert.js:29:9)  
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)  
      at Context.<anonymous> (test/index-test.js:48:52)

**Comment by AnnJohn** [comment]
hi @jenlaister could you use "Ask a Question" in Learn and someone from our team will help you out right away. thanks!
