### ISSUE TITLE
Strange error occurring while trying to learn test 'Intro To Functions' lab. 

### ISSUE THREAD

**Issue by ElphC350** [learn-co-curriculum/javascript-intro-to-functions-lab#64]
Hello! I have finished the code for 'Intro To Functions' lab and it went though as 'all tests passed' on the lesson web page, I was able to submit it and move onto the next lesson, however every time I run it I get this message:

```
> java-script-intro-to-functions-lab@0.1.0 test /home/tkcorrea89-110957/code/labs/javascript-intro-to-functions-lab-bootcamp-prep-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json
 0   __,------,
 1   __|  /\_/\
 0   _~|_( x .x)
     _ ""  ""
  0 passing (295ms)
  1 failing
  1)  "before all" hook:
     SyntaxError: /home/tkcorrea89-110957/code/labs/javascript-intro-to-functions-lab-bootcamp-prep-000/index.js: Unexpected token, expected ; (10:8)
     8 | }
     9 |
  > 10 | funtion logShout(string) {
       |         ^
    11 |   console.log(string)
    12 | }
    13 |
      at Parser.pp$5.raise (node_modules/babylon/lib/index.js:4454:13)
      at Parser.pp.unexpected (node_modules/babylon/lib/index.js:1761:8)
      at Parser.pp.semicolon (node_modules/babylon/lib/index.js:1742:38)
      at Parser.pp$1.parseExpressionStatement (node_modules/babylon/lib/index.js:2236:8)
      at Parser.pp$1.parseStatement (node_modules/babylon/lib/index.js:1911:17)
      at Parser.pp$1.parseBlockBody (node_modules/babylon/lib/index.js:2268:21)
      at Parser.pp$1.parseTopLevel (node_modules/babylon/lib/index.js:1778:8)
      at Parser.parse (node_modules/babylon/lib/index.js:1673:17)
      at parse (node_modules/babylon/lib/index.js:7246:37)
      at File.parse (node_modules/babel-core/lib/transformation/file/index.js:517:15)
      at File.parseCode (node_modules/babel-core/lib/transformation/file/index.js:602:20)
      at node_modules/babel-core/lib/transformation/pipeline.js:49:12
      at File.wrap (node_modules/babel-core/lib/transformation/file/index.js:564:16)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:47:17)
      at Object.transformFileSync (node_modules/babel-core/lib/api/node.js:152:10)
      at Context.<anonymous> (test/root.js:8:29)
npm ERR! Test failed.  See above for more details.
```

No matter what I do I get it. I even tried deleting the lesson files and starting fresh, and It worked fine for the first two tests and then began giving me this error again.

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
